# Extra autostart processes
# exec-once = uwsm app -- hypridle
# exec-once = uwsm app -- mako
# exec-once = uwsm app -- waybar
# exec-once = uwsm app -- fcitx5
# exec-once = uwsm app -- swayosd-server
exec-once = uwsm app -- qs -c noctalia-shell
exec-once = uwsm app -- wl-paste --type text --watch cliphist store
exec-once = uwsm app -- wl-paste --type image --watch cliphist store
exec-once = uwsm app -- flameshot
exec-once = uwsm app -- easyeffects -w
exec-once = uwsm app -- env __GL_THREADED_OPTIMIZATIONS=0 linux-wallpaperengine --screen-root DP-5 --scaling fill -bg /home/master/.steam/root/steamapps/workshop/content/431960/2954470946 --disable-particles --fps 30 --no-audio-processing
exec-once = uwsm app -- env __GL_THREADED_OPTIMIZATIONS=0 linux-wallpaperengine --screen-root DP-6 --scaling fill -args -bg /home/master/.steam/root/steamapps/workshop/content/431960/3197745768 --disable-particles --fps 30 --no-audio-processing
