$ipc = qs -c noctalia-shell ipc call
# Application bindings
bind = SUPER, return, exec, ghostty
bind = SUPER, R, exec, nemo

# If your web app url contains #, type it as ## to prevent hyperland treat it as comments
# bindd = SUPER SHIFT, C, WhatsApp, exec, hyprland-launch-or-focus WhatsApp "hyprland-launch-webapp 'https://web.whatsapp.com/'"
# bindd = SUPER SHIFT, E, Excalidraw, exec, hyprland-launch-or-focus Excalidraw "hyprland-launch-webapp 'https://excalidraw.com/'"
# bindd = SUPER SHIFT, M, Music, exec, hyprland-launch-or-focus spotify

bind = SUPER, SPACE, exec, $ipc launcher toggle

bind = SUPER, I, fullscreen
bind = SUPER SHIFT, PERIOD, togglefloating, #Float Mode
bind = SUPER SHIFT, X, exec, XDG_CURRENT_DESKTOP=sway flameshot gui

# Desktop zooming or magnifier
bind = ALT HOME, mouse_down, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor * 2.0}')"
bind = ALT HOME, mouse_up, exec, hyprctl keyword cursor:zoom_factor "$(hyprctl getoption cursor:zoom_factor | awk 'NR==1 {factor = $2; if (factor < 1) {factor = 1}; print factor / 2.0}')"

# FEATURES / EXTRAS (UserScripts)
bind = SUPER, W, exec, waypaper
bind = SUPER, E, exec, $ipc settings toggle
bind = SUPER, V, exec, $ipc launcher clipboard
bind = SUPER, B, exec, hyprland-toggle-blur

bind = SUPER, Q, killactive, # close active (not kill)

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = SUPER, mouse:272, movewindow # NOTE: mouse:272 = left click
bindm = SUPER, mouse:273, resizewindow # NOTE: mouse:272 = right click
