# https://wiki.hyprland.org/Configuring/Variables/#general
animations {
  enabled = no, please :)
}

general {
  # No gaps between windows
  border_size = 0

  gaps_in = 0
  gaps_out = 0

  # Use master layout instead of dwindle
  # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
  # Use round window corners
  # rounding = 8
  active_opacity = 1.0
  inactive_opacity = 1.0
  fullscreen_opacity = 1.0

  blur {
    enabled = true
    size = 6
    passes = 2
    # brightness = 1.0
    # contrast = 1.0
    ignore_opacity = false
    new_optimizations = false
    special = true
    popups = true
  }

}
