windowrule {
  name = maxall
  suppress_event = maximize
  match:class = .*
}


# Just dash of opacity by default
# windowrule = opacity 0.97 0.9, class:.*

# Fix some dragging issues with XWayland
windowrule {
  name = drag-on-deez-nutz
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

# App-specific tweaks
source = ~/.config/hypr/apps/browser.conf
source = ~/.config/hypr/apps/pip.conf
source = ~/.config/hypr/apps/waypaper.conf
source = ~/.config/hypr/apps/retroarch.conf
source = ~/.config/hypr/apps/system.conf
source = ~/.config/hypr/apps/terminals.conf
source = ~/.config/hypr/apps/walker.conf
