# Floating windows

# windowrule = size 800 600, tag:floating-window



# Fullscreen screensaver
windowrule {
  name = screensaver
  fullscreen = on
  match:class = Screensaver
}


# No transparency on media windows
windowrule {
  name = schmutz
  opacity = 1 1
  match:class = ^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$
}
